apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: gohelloworld-pipeline-run
  namespace: default
spec:
  pipelineRef:
    name: gohelloworld-pipeline
  trigger:
    type: manual
  resources:
  - name: test
    inputs:
    - name: workspace
      resourceRef:
        name: go-helloworld-git
    outputs:
    - name: workspace
      resourceRef:
        name: go-helloworld-git
  - name: build
    inputs:
    - name: workspace
      resourceRef:
        name: go-helloworld-git
    outputs:
    - name: workspace
      resourceRef:
        name: go-helloworld-git