apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gohelloworld
  labels: {app: gohelloworld}
spec:
  replicas: 1
  template:
    metadata: {labels: {app: gohelloworld}}
    spec:
      containers:
      - name: news
        image: gcr.io/my_gcr_project/gohelloworld:latest
        command:
        ports:
          - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: gohelllworld
spec:
  type: LoadBalancer
  selector:
    app: gohelloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080