---    
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: go-helloworld-git
spec:    
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/pivotal-nader-ziada/gohelloworld
---    
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: go-helloworld-image
  namespace: default
spec:  
  type: image
  params:
  - name: url
    value: gcr.io/cf-elafros-dog/gohelloworld
---    
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: go-helloworld-test-cluster
  namespace: default
spec:  
  type: cluster
  params:
  - name: clusterName
    value: nader-knative-test     
  - name: url
    value: https://35.225.217.172:8443   
  secrets:  
  - fieldName: username
    secretKey: username
    secretName:  target-cluster-secrets
  - fieldName: token
    secretKey: token
    secretName:  target-cluster-secrets
  - fieldName: cadata
    secretKey: cadata
    secretName:  target-cluster-secrets    