apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: unit-test
  namespace: default
spec:
  inputs:
    resources:
    - name: workspace
      type: git
  buildSpec:
    steps:
    - name: run-tests
      image: golang
      command: 
      - go
      args: ["test", "./..."]