apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: build-image
  namespace: default
spec:
  inputs:
    resources:
    - name: workspace
      type: git
    params:
    - name: pathToDockerfile
      description: The path to the dockerfile to build
      default: /workspace/Dockerfile      
    - name: outputImage
      description: image to be uploaded
  outputs:
    resources:
    - name: workspace
      type: git
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    command: 
    - /kaniko/executor
    args:
    - --dockerfile=${inputs.params.pathToDockerfile}
    - --destination=${inputs.params.outputImage}
