apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: deploy-image
  namespace: default
spec:
  inputs:
    resources:
    - name: workspace
      type: git
    - name: dockerimage
      type: image
    # - name: testcluster
    #   type: cluster    
  buildSpec:
    steps:
    - name: deploy
      image: nziada/gohelloworld
      command: 
      - kubectl
      args: ["apply", "f", "service.yaml"]