apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineParams
metadata:
  name: gohelloworld-pipelineparams
  namespace: default
spec:
  # serviceAccount: 'demoServiceAccount'
  results:
  runs:
    name: 'runsBucket'
    type: 'gcs'
    url: 'gcs://somebucket/results/runs'
  logs:
    name: 'logBucket'
    type: 'gcs'
    url: 'gcs://somebucket/results/logs'
  tests:
    name: 'testBucket'
    type: 'gcs'
    url: 'gcs://somebucket/results/test400s'
